version: "3.9"

services:
  secure-python:
    build:
      context: .
      dockerfile: lanes/python/Dockerfile
    image: secure-python:latest
    container_name: spe-python
    ports: ["8500:8500"]
    restart: unless-stopped
    cpus: "1.0"
    mem_limit: "512m"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs: [/tmp]
    networks: [spe-net]

  secure-rust:
    build:
      context: .
      dockerfile: lanes/rust/Dockerfile
    image: secure-rust:latest
    container_name: spe-rust
    ports: ["8501:8501"]
    restart: unless-stopped
    cpus: "1.0"
    mem_limit: "256m"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs: [/tmp]
    networks: [spe-net]

  secure-wasm:
    build:
      context: .
      dockerfile: lanes/wasm/Dockerfile
    image: secure-wasm:latest
    container_name: spe-wasm
    ports: ["8502:8502"]
    restart: unless-stopped
    cpus: "1.0"
    mem_limit: "512m"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs: [/tmp]
    networks: [spe-net]

networks:
  spe-net:
    driver: bridge